### ISSUE TITLE
no download with txid10090 (big size)

### ISSUE THREAD

**Issue by hmkim** [StuntsPT/NCBI_Mass_Downloader#15]
For example, this command can't download the data for searching.
$ python NCBI_downloader.py -d nucleotide -q "txid10090[Organism]" -o txid10090.fa

Could you check this problem?

**Comment by StuntsPT** [comment]
On it. Will report back once I know more.
Thanks for reporting.

**Comment by StuntsPT** [comment]
I have tried your query.
It takes quite a while to start (~40 minutes here) but it does happen.
Yes, the program will work silently for a while (I'll probably change that), especially with big sized queries like the one you provided, but it's still working.
This is happening because NCBI has deprecated GIs in favour of accession numbers (and currently it's not possible to use GIs to query the database), however, they did not fully updated the API, and `esearch`, which is used to convert a text query to database entries still does not return accession numbers, but only GIs.
As such, until the API is completely implemented on NCBI's side, I have provided a workaround, which is getting the GI list and converting it to Accessions numbers using `efetch` (which is another piece of the API). However, this can only be done in "chunks" of 10000 entries each time, and we are not allowed to make more than 3 database queries per second, which means that this first "translation" step takes quite a while.
There is really not much I can do right now other than providing a message to assure useres the program did not crash, but is still working. At least until the API is fully implemented.

Here are some links you may find relevant:
https://github.com/biopython/biopython/issues/926#issuecomment-256032486
https://ncbiinsights.ncbi.nlm.nih.gov/2016/07/15/ncbi-is-phasing-out-sequence-gis-heres-what-you-need-to-know/

I will leave the issue open, until I can solve the problem, instead of working around it.

**Comment by StuntsPT** [comment]
Please confirm that the latest master from git provides an acceptable workaround for you!

**Comment by hmkim** [comment]
Thanks for your feedback. I running the program with the latest master.

```
Translating GIs to Accessions: Record 1 to 10000 of 1846554.
Translating GIs to Accessions: Record 10001 to 20000 of 1846554.
Translating GIs to Accessions: Record 20001 to 30000 of 1846554.
...
```

and my hosting server have the only 1G ram size. 
If I have the big size query, how can I handle this on my server ? 
What is the easiest way to solve the memory issue? (may be changing the computer spec?)

**Comment by StuntsPT** [comment]
Humm... that's going to be a tough one.
I'm not sure there is a way to "dump" what urllib is getting directly into a file.
Each of those "chunks" you are getting gets written to the disk and evicted from the memory on every cycle.
What is happening is that the cycle that downloads records 132001 to 135000 gets larger than whatever memory you have available.
As a workaround you can do the following:
Go to [this line](https://github.com/StuntsPT/NCBI_Mass_Downloader/blob/master/back_end.py#L273) on your copy of the program and reduce the batch_size variable to something smaller, like 1000, or even 500 if that is still too large.
The download will take longer, but with a smaller batch it **might** fit into the memory you have.
If you can, you may also wish to experiment with [zram](https://wiki.archlinux.org/index.php/Improving_performance#RAM_and_swap) if you are on linux, which will compress the data in memory  - more capacity in exchange for CPU usage (but you need full control of the machine AFAIK).
You might also want to increase the swap partition size, or use a sawpfile (also, if you are on linux, I'm not sure about alternatives on other OSes).

**Comment by hmkim** [comment]
Can you check this snippet?

(http://stackoverflow.com/questions/1517616/stream-large-binary-files-with-urllib2-to-file)
```
# from urllib2 import urlopen # Python 2
from urllib.request import urlopen # Python 3

response = urlopen(url)
CHUNK = 16 * 1024
with open(file, 'wb') as f:
    while True:
        chunk = response.read(CHUNK)
        if not chunk:
            break
        f.write(chunk)
```

I'll try to run the program as you mentioned.

> Go to this line on your copy of the program and reduce the batch_size variable to something smaller, like 1000, or even 500 if that is still too large.

**Comment by StuntsPT** [comment]
I don't think we can go that low level here.
Also, the problem is not the chunks of bytes that are being retrieved, but rather their accumulation in a string that need to be parsed for errors.
If you reduce the number of sequenced per downloaded batch, it **should** suffice (unless there is a batch of 500 sequences that cannot fit into the 1Gb of memory you have available. In that case you would have to go lower, like 100 seqs per batch, but your download will take quite a while).
Let me know if a batch of 500 worked. =-)

**Comment by hmkim** [comment]
Okay, I changed my download server to have more memory than 1Gb. I finished my job successfully.

Thank you!

**Comment by StuntsPT** [comment]
Great to know!
Just out of curiosity, how much RAM did you end up requiring for such a large download?
